'use client';

import React from 'react';
import { Sparkles, Ticket, GitPullRequest, ShieldCheck } from 'lucide-react';

export const AiCapabilitiesPanel: React.FC = () => {
  return (
    <section className="py-20 border-b border-[#D9D9D9] bg-[#F2F2F2] relative overflow-hidden text-[#1F1F1F]">
      <div className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3 max-w-2xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md border border-[#D9D9D9] bg-white text-[#174D38] text-xs font-mono font-medium shadow-xs">
            Background AI Intelligence
          </div>
          <h2 className="text-3xl md:text-4xl font-semibold text-[#1F1F1F] tracking-tight">
            AI Digest Engine
          </h2>
          <p className="text-xs md:text-sm text-[#6B7280]">
            Subtle, non-intrusive AI synthesis summarizing daily activity, unblocking pull requests, and identifying high-priority support tickets.
          </p>
        </div>

        {/* AI Preview Panel */}
        <div className="max-w-4xl mx-auto rounded-[10px] border border-[#D9D9D9] bg-white p-6 space-y-6 shadow-xs">
          <div className="flex items-center justify-between border-b border-[#D9D9D9] pb-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-md bg-[#F2F2F2] border border-[#D9D9D9] flex items-center justify-center text-[#174D38]">
                <Sparkles className="w-4 h-4" />
              </div>
              <div>
                <h3 className="font-semibold text-sm text-[#1F1F1F]">Today&apos;s Executive AI Briefing</h3>
                <p className="text-[11px] font-mono text-[#6B7280]">Generated by Gemini LLM Worker • Org: Acme Corp</p>
              </div>
            </div>
            <span className="px-2.5 py-1 rounded text-xs font-mono font-medium bg-[#F2F2F2] text-[#174D38] border border-[#D9D9D9]">
              Live Synthesis
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 rounded-md border border-[#D9D9D9] bg-[#F2F2F2]/50 space-y-2">
              <div className="flex items-center gap-2 text-[#174D38] font-mono text-xs font-semibold">
                <Ticket className="w-3.5 h-3.5" />
                <span>3 High-Priority Tickets</span>
              </div>
              <p className="text-xs text-[#6B7280]">
                2 customer tickets approaching SLA limit. 1 ticket awaiting engineering triage.
              </p>
            </div>

            <div className="p-4 rounded-md border border-[#D9D9D9] bg-[#F2F2F2]/50 space-y-2">
              <div className="flex items-center gap-2 text-[#174D38] font-mono text-xs font-semibold">
                <GitPullRequest className="w-3.5 h-3.5" />
                <span>2 Pending Approvals</span>
              </div>
              <p className="text-xs text-[#6B7280]">
                PR #402 requires 1 additional approval before production merge deadline.
              </p>
            </div>

            <div className="p-4 rounded-md border border-[#D9D9D9] bg-[#F2F2F2]/50 space-y-2">
              <div className="flex items-center gap-2 text-[#15803D] font-mono text-xs font-semibold">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>1 Org Invitation</span>
              </div>
              <p className="text-xs text-[#6B7280]">
                Partner org Stripe Inc requested READ access to Shared Review Console.
              </p>
            </div>
          </div>

          <div className="p-4 rounded-md border border-[#D9D9D9] bg-[#F2F2F2]/50 text-xs text-[#1F1F1F] leading-relaxed font-mono">
            <span className="text-[#174D38] font-semibold">&gt; Summary:</span> Operational risk is low. All security audit streams report 100% compliance. Recommending immediate review of PR #402 to clear engineering backlog.
          </div>
        </div>
      </div>
    </section>
  );
};
