'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.DEMO_USERS = void 0;
exports.DEMO_USERS = [
  {
    id: 'demo-super-admin',
    roleTitle: 'Platform Super Admin',
    email: 'superadmin@platform.demo',
    password: 'Demo@12345',
    firstName: 'Super',
    lastName: 'Admin',
    name: 'Super Admin',
    avatar: 'SA',
    organizationName: 'Global Platform',
    organizationSlug: 'global-platform',
    roleBadge: 'SUPER_ADMIN',
    description: 'Platform-wide governance, global management, no organization membership.',
    redirectRoute: '/dashboard',
    themeColor: 'indigo',
    iconName: 'ShieldCheck',
  },
  {
    id: 'demo-org-admin-acme',
    roleTitle: 'Organization Admin (Acme)',
    email: 'admin@acme.demo',
    password: 'Demo@12345',
    firstName: 'Aarav',
    lastName: 'Mehta',
    name: 'Aarav Mehta',
    avatar: 'AM',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'ADMIN',
    description: 'Manage Acme Technologies users, tickets, and organization settings.',
    redirectRoute: '/dashboard',
    themeColor: 'blue',
    iconName: 'Building2',
  },
  {
    id: 'demo-org-admin-nova',
    roleTitle: 'Organization Admin (Nova)',
    email: 'admin@nova.demo',
    password: 'Demo@12345',
    firstName: 'Ananya',
    lastName: 'Iyer',
    name: 'Ananya Iyer',
    avatar: 'AI',
    organizationName: 'Nova Healthcare',
    organizationSlug: 'nova-health',
    roleBadge: 'ADMIN',
    description: 'Manage Nova Healthcare users, tickets, and organization settings.',
    redirectRoute: '/dashboard',
    themeColor: 'blue',
    iconName: 'Building2',
  },
  {
    id: 'demo-support-agent-1-acme',
    roleTitle: 'Support Agent 1 (Acme)',
    email: 'support1@acme.demo',
    password: 'Demo@12345',
    firstName: 'Rohan',
    lastName: 'Gupta',
    name: 'Rohan Gupta',
    avatar: 'RG',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'SUPPORT_AGENT',
    description: 'Handle Acme support tickets, SLA tracking, and ticket resolution.',
    redirectRoute: '/dashboard',
    themeColor: 'cyan',
    iconName: 'Headphones',
  },
  {
    id: 'demo-support-agent-2-acme',
    roleTitle: 'Support Agent 2 (Acme)',
    email: 'support2@acme.demo',
    password: 'Demo@12345',
    firstName: 'Karan',
    lastName: 'Sharma',
    name: 'Karan Sharma',
    avatar: 'KS',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'SUPPORT_AGENT',
    description: 'Manage support tickets and activity timelines for Acme.',
    redirectRoute: '/dashboard',
    themeColor: 'cyan',
    iconName: 'Headphones',
  },
  {
    id: 'demo-support-agent-nova',
    roleTitle: 'Support Agent (Nova)',
    email: 'support@nova.demo',
    password: 'Demo@12345',
    firstName: 'Siddharth',
    lastName: 'Rao',
    name: 'Siddharth Rao',
    avatar: 'SR',
    organizationName: 'Nova Healthcare',
    organizationSlug: 'nova-health',
    roleBadge: 'SUPPORT_AGENT',
    description: 'Handle customer support tickets for Nova Healthcare.',
    redirectRoute: '/dashboard',
    themeColor: 'cyan',
    iconName: 'Headphones',
  },
  {
    id: 'demo-reviewer-acme',
    roleTitle: 'Reviewer (Acme)',
    email: 'reviewer@acme.demo',
    password: 'Demo@12345',
    firstName: 'Priya',
    lastName: 'Sharma',
    name: 'Priya Sharma',
    avatar: 'PS',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'REVIEWER',
    description:
      'Review and approve pull requests, diff inspection, and merge validation for Acme.',
    redirectRoute: '/dashboard',
    themeColor: 'purple',
    iconName: 'GitPullRequest',
  },
  {
    id: 'demo-reviewer-nova',
    roleTitle: 'Reviewer (Nova)',
    email: 'reviewer@nova.demo',
    password: 'Demo@12345',
    firstName: 'Neha',
    lastName: 'Verma',
    name: 'Neha Verma',
    avatar: 'NV',
    organizationName: 'Nova Healthcare',
    organizationSlug: 'nova-health',
    roleBadge: 'REVIEWER',
    description: 'Review and approve code change proposals for Nova Healthcare.',
    redirectRoute: '/dashboard',
    themeColor: 'purple',
    iconName: 'GitPullRequest',
  },
  {
    id: 'demo-guest-nova',
    roleTitle: 'Guest (Nova)',
    email: 'guest@nova.demo',
    password: 'Demo@12345',
    firstName: 'Vikram',
    lastName: 'Malhotra',
    name: 'Vikram Malhotra',
    avatar: 'VM',
    organizationName: 'Nova Healthcare',
    organizationSlug: 'nova-health',
    roleBadge: 'GUEST',
    description: 'Access cross-organization shared resources only.',
    redirectRoute: '/dashboard',
    themeColor: 'amber',
    iconName: 'UserCheck',
  },
  {
    id: 'demo-auditor-acme',
    roleTitle: 'Auditor (Acme)',
    email: 'auditor@acme.demo',
    password: 'Demo@12345',
    firstName: 'Devansh',
    lastName: 'Verma',
    name: 'Devansh Verma',
    avatar: 'DV',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'AUDITOR',
    description: 'Read-only compliance and immutable audit log inspection for Acme.',
    redirectRoute: '/dashboard',
    themeColor: 'emerald',
    iconName: 'Eye',
  },
];
