'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.DEMO_USERS = void 0;
exports.DEMO_USERS = [
  {
    id: 'demo-super-admin',
    roleTitle: 'Platform Super Admin',
    email: 'superadmin@platform.demo',
    password: 'Demo@12345',
    firstName: 'Super',
    lastName: 'Admin',
    name: 'Super Admin',
    avatar: 'SA',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'SUPER_ADMIN',
    description: 'Manage the entire platform, multi-tenant governance, and global audit oversight.',
    redirectRoute: '/dashboard',
    themeColor: 'indigo',
    iconName: 'ShieldCheck',
  },
  {
    id: 'demo-org-admin-acme',
    roleTitle: 'Organization Admin (Acme)',
    email: 'admin@acme.demo',
    password: 'Demo@12345',
    firstName: 'Aarav',
    lastName: 'Mehta',
    name: 'Aarav Mehta',
    avatar: 'AM',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'ADMIN',
    description: 'Manage users and organization settings for Acme Technologies.',
    redirectRoute: '/dashboard',
    themeColor: 'blue',
    iconName: 'Building2',
  },
  {
    id: 'demo-support-agent',
    roleTitle: 'Support Agent',
    email: 'support@acme.demo',
    password: 'Demo@12345',
    firstName: 'Rohan',
    lastName: 'Gupta',
    name: 'Rohan Gupta',
    avatar: 'RG',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'SUPPORT_AGENT',
    description: 'Handle customer support tickets, SLA scoring, and customer replies.',
    redirectRoute: '/dashboard',
    themeColor: 'cyan',
    iconName: 'Ticket',
  },
  {
    id: 'demo-reviewer',
    roleTitle: 'Reviewer',
    email: 'reviewer@acme.demo',
    password: 'Demo@12345',
    firstName: 'Priya',
    lastName: 'Sharma',
    name: 'Priya Sharma',
    avatar: 'PS',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'REVIEWER',
    description: 'Approve and merge code reviews, inspect visual diffs, and authorize releases.',
    redirectRoute: '/dashboard',
    themeColor: 'purple',
    iconName: 'GitPullRequest',
  },
  {
    id: 'demo-org-admin-nova',
    roleTitle: 'Organization Admin (Nova)',
    email: 'admin@nova.demo',
    password: 'Demo@12345',
    firstName: 'Ananya',
    lastName: 'Iyer',
    name: 'Ananya Iyer',
    avatar: 'AI',
    organizationName: 'Nova Health Systems',
    organizationSlug: 'nova-health',
    roleBadge: 'ADMIN',
    description: 'Manage users and organization settings for Nova Health Systems.',
    redirectRoute: '/dashboard',
    themeColor: 'blue',
    iconName: 'Building2',
  },
  {
    id: 'demo-guest',
    roleTitle: 'Guest Collaborator',
    email: 'guest@nova.demo',
    password: 'Demo@12345',
    firstName: 'Vikram',
    lastName: 'Malhotra',
    name: 'Vikram Malhotra',
    avatar: 'VM',
    organizationName: 'Nova Health Systems',
    organizationSlug: 'nova-health',
    roleBadge: 'GUEST',
    description: 'Access shared resources securely with cross-organization partner read access.',
    redirectRoute: '/dashboard',
    themeColor: 'amber',
    iconName: 'Users',
  },
  {
    id: 'demo-auditor',
    roleTitle: 'Read-Only Auditor',
    email: 'auditor@platform.demo',
    password: 'Demo@12345',
    firstName: 'Devansh',
    lastName: 'Verma',
    name: 'Devansh Verma',
    avatar: 'DV',
    organizationName: 'Platform Audit Corp',
    organizationSlug: 'acme-tech',
    roleBadge: 'AUDITOR',
    description: 'Read-only compliance and audit access with immutable log stream inspection.',
    redirectRoute: '/dashboard',
    themeColor: 'emerald',
    iconName: 'Lock',
  },
  {
    id: 'demo-ai-user',
    roleTitle: 'AI Demo User',
    email: 'ai@acme.demo',
    password: 'Demo@12345',
    firstName: 'Gemini',
    lastName: 'AI',
    name: 'AI Agent',
    avatar: 'AI',
    organizationName: 'Acme Technologies',
    organizationSlug: 'acme-tech',
    roleBadge: 'ADMIN',
    description:
      'Simulated AI worker account for background summaries and automated ticket scoring.',
    redirectRoute: '/dashboard',
    themeColor: 'cyan',
    iconName: 'Sparkles',
  },
];
//# sourceMappingURL=demoUsers.js.map
