export interface DemoUser {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  roleTitle: string;
  roleBadge: string;
  organizationName: string;
  description: string;
  iconName: string;
  avatar?: string;
  organizationSlug?: string;
  password?: string;
}

export type DemoUserConfig = DemoUser;

export const DEMO_PASSWORD = 'Demo@123';

export const DEMO_USERS: DemoUserConfig[] = [
  {
    id: 'demo-superadmin',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'superadmin@demo.com',
    role: 'SUPER_ADMIN',
    roleTitle: 'Super Admin',
    roleBadge: 'SUPER_ADMIN',
    organizationName: 'Global Platform',
    description: 'System-wide super admin access across all organizations and system settings.',
    iconName: 'ShieldCheck',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-admin-acme',
    firstName: 'Ananya',
    lastName: 'Patel',
    email: 'admin@acme.com',
    role: 'ADMIN',
    roleTitle: 'Organization Admin',
    roleBadge: 'ADMIN',
    organizationName: 'Acme Corporation',
    description: 'Full admin rights for Acme Corporation team management and governance.',
    iconName: 'Building2',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-admin-technova',
    firstName: 'Vikramaditya',
    lastName: 'Verma',
    email: 'admin@technova.com',
    role: 'ADMIN',
    roleTitle: 'Organization Admin',
    roleBadge: 'ADMIN',
    organizationName: 'TechNova Solutions',
    description: 'Organization administrator for TechNova Solutions enterprise team.',
    iconName: 'Building2',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'technova-solutions',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-manager-acme',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'manager@acme.com',
    role: 'ADMIN',
    roleTitle: 'Engineering Manager',
    roleBadge: 'MANAGER',
    organizationName: 'Acme Corporation',
    description: 'Engineering manager managing sprint tickets, team velocity, and projects.',
    iconName: 'UserCheck',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-manager-technova',
    firstName: 'Meera',
    lastName: 'Iyer',
    email: 'manager@technova.com',
    role: 'ADMIN',
    roleTitle: 'Product Manager',
    roleBadge: 'MANAGER',
    organizationName: 'TechNova Solutions',
    description: 'Product manager leading TechNova core products and releases.',
    iconName: 'UserCheck',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'technova-solutions',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-dev1-acme',
    firstName: 'Rohan',
    lastName: 'Gupta',
    email: 'dev1@acme.com',
    role: 'REVIEWER',
    roleTitle: 'Senior Developer',
    roleBadge: 'DEVELOPER',
    organizationName: 'Acme Corporation',
    description: 'Lead software engineer writing code and reviewing pull requests.',
    iconName: 'GitPullRequest',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-dev2-acme',
    firstName: 'Deepa',
    lastName: 'Reddy',
    email: 'dev2@acme.com',
    role: 'REVIEWER',
    roleTitle: 'Frontend Developer',
    roleBadge: 'DEVELOPER',
    organizationName: 'Acme Corporation',
    description: 'UI engineer crafting frontend components and design systems.',
    iconName: 'GitPullRequest',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-dev1-technova',
    firstName: 'Aditya',
    lastName: 'Deshmukh',
    email: 'dev1@technova.com',
    role: 'REVIEWER',
    roleTitle: 'Fullstack Developer',
    roleBadge: 'DEVELOPER',
    organizationName: 'TechNova Solutions',
    description: 'Fullstack engineer at TechNova Solutions.',
    iconName: 'GitPullRequest',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'technova-solutions',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-security-acme',
    firstName: 'Siddharth',
    lastName: 'Malhotra',
    email: 'security@acme.com',
    role: 'AUDITOR',
    roleTitle: 'Security Analyst',
    roleBadge: 'SECURITY',
    organizationName: 'Acme Corporation',
    description: 'Security analyst monitoring anomaly detection, logs, and threats.',
    iconName: 'ShieldCheck',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-auditor-acme',
    firstName: 'Aditya',
    lastName: 'Nair',
    email: 'auditor@acme.com',
    role: 'AUDITOR',
    roleTitle: 'Compliance Auditor',
    roleBadge: 'AUDITOR',
    organizationName: 'Acme Corporation',
    description: 'Compliance auditor reviewing audit trails and security reports.',
    iconName: 'Eye',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-support-acme',
    firstName: 'Sunita',
    lastName: 'Rao',
    email: 'support@acme.com',
    role: 'SUPPORT_AGENT',
    roleTitle: 'Support Agent',
    roleBadge: 'SUPPORT',
    organizationName: 'Acme Corporation',
    description: 'Customer support agent handling customer tickets and queries.',
    iconName: 'Headphones',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
  {
    id: 'demo-viewer-acme',
    firstName: 'Varun',
    lastName: 'Mehta',
    email: 'viewer@acme.com',
    role: 'GUEST',
    roleTitle: 'Read-only Viewer',
    roleBadge: 'VIEWER',
    organizationName: 'Acme Corporation',
    description: 'Read-only access for stakeholder reviews and viewing dashboards.',
    iconName: 'Eye',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    organizationSlug: 'acme-corp',
    password: DEMO_PASSWORD,
  },
];
