'use client';

import React from 'react';
import { Sparkles, Ticket, GitPullRequest, ShieldCheck } from 'lucide-react';

export const AiCapabilitiesPanel: React.FC = () => {
  return (
    <section className="py-20 border-b border-border bg-background relative overflow-hidden text-text-primary">
      <div className="max-w-7xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-3 max-w-2xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md border border-border bg-surface text-primary text-xs font-mono font-medium shadow-xs">
            Background AI Intelligence
          </div>
          <h2 className="text-3xl md:text-4xl font-semibold text-text-primary tracking-tight">
            AI Digest Engine
          </h2>
          <p className="text-xs md:text-sm text-text-secondary">
            Subtle, non-intrusive AI synthesis summarizing daily activity, unblocking pull requests,
            and identifying high-priority support tickets.
          </p>
        </div>

        {/* AI Preview Panel */}
        <div className="max-w-4xl mx-auto rounded-[10px] border border-border bg-surface p-6 space-y-6 shadow-xs">
          <div className="flex items-center justify-between border-b border-border pb-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-md bg-surface-secondary border border-border flex items-center justify-center text-primary">
                <Sparkles className="w-4 h-4" />
              </div>
              <div>
                <h3 className="font-semibold text-sm text-text-primary">
                  Today&apos;s Executive AI Briefing
                </h3>
                <p className="text-[11px] font-mono text-text-secondary">
                  Generated by Gemini LLM Worker • Org: Acme Corp
                </p>
              </div>
            </div>
            <span className="px-2.5 py-1 rounded text-xs font-mono font-medium bg-surface-secondary text-primary border border-border">
              Live Synthesis
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 rounded-md border border-border bg-surface-secondary/50 space-y-2">
              <div className="flex items-center gap-2 text-primary font-mono text-xs font-semibold">
                <Ticket className="w-3.5 h-3.5" />
                <span>3 High-Priority Tickets</span>
              </div>
              <p className="text-xs text-text-secondary">
                2 customer tickets approaching SLA limit. 1 ticket awaiting engineering triage.
              </p>
            </div>

            <div className="p-4 rounded-md border border-border bg-surface-secondary/50 space-y-2">
              <div className="flex items-center gap-2 text-primary font-mono text-xs font-semibold">
                <GitPullRequest className="w-3.5 h-3.5" />
                <span>2 Pending Approvals</span>
              </div>
              <p className="text-xs text-text-secondary">
                PR #402 requires 1 additional approval before production merge deadline.
              </p>
            </div>

            <div className="p-4 rounded-md border border-border bg-surface-secondary/50 space-y-2">
              <div className="flex items-center gap-2 text-success font-mono text-xs font-semibold">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>1 Org Invitation</span>
              </div>
              <p className="text-xs text-text-secondary">
                Partner org Stripe Inc requested READ access to Shared Review Console.
              </p>
            </div>
          </div>

          <div className="p-4 rounded-md border border-border bg-surface-secondary/50 text-xs text-text-primary leading-relaxed font-mono">
            <span className="text-primary font-semibold">&gt; Summary:</span> Operational risk is
            low. All security audit streams report 100% compliance. Recommending immediate review of
            PR #402 to clear engineering backlog.
          </div>
        </div>
      </div>
    </section>
  );
};
